version: "2.1"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  app:
    build: ./
    links:
      - postgres:postgres
    ports:
      - 8080:8080
